/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h2>David Morales</h2>
        <nav>
          <ul>
            <li>
              <a href="#">Home</a>
              <span />
            </li>
            <li>
              <a href="#">About me</a>
              <span />
            </li>
            <li>
              <a href="#">Skills</a>
              <span />
            </li>
            <li>
              <a href="#">Experience</a>
              <span />
            </li>
            <li>
              <a href="#">Projects</a>
              <span />
            </li>
            <li>
              <a href="#">Contact</a>
              <span />
            </li>
          </ul>

          <button>
            <span />
            <span />
            <span />
          </button>
        </nav>
      </header>
      <main>
        <section className="home">
          <div className="container-large">
            <div className="header_layout">
              <div className="div-header-layout">
                <p className="header-p">HELLO, I AM David Morales</p>
                <h1>
                  Welcome to my web portfolio!
                  <span className=""> </span>
                </h1>
                <p className="paragraph-p">
                  I am a full stack web developer passionate about creating
                  innovative and efficient solutions for my clients. Throughout
                  my career, I have worked on a wide range of projects, from
                  small websites to large enterprise applications.
                </p>
                <div className="button-group">
                  <a href="#aboutMe" className="principal-button">
                    About me
                  </a>
                  <a href="#skills" className="secondary-button">
                    <div>Skills</div>
                    <div className="ball">
                      <svg
                        width="1.25rem"
                        height="1.5rem"
                        viewBox="0 0 16 16"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M6 3L11 8L6 13"
                          stroke="CurrentColor"
                          stroke-width="1.5"
                        ></path>
                      </svg>
                    </div>
                  </a>
                </div>
              </div>
              <div className="div-header-layout">
                <img
                  src="/main-image.png"
                  alt="main image"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
