/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import { Header, Home } from "@/components";
import { AboutMe } from "@/components/AboutMe";
import StarsCanvas from "@/components/canvas/starts";
import Head from "next/head";

export default function App() {
  return (
    <>
      <Head>
        <title>David Morales | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Home />
        <AboutMe />
      </main>
    </>
  );
}
